#!/usr/bin/env python3
"""Regenerate src/data/faq.generated.ts from the client's FAQ markdown database.

Usage:  python3 scripts/faq-from-markdown.py "<path to FAQs .md>" [src/data/faq.generated.ts]

Expected markdown shape (one block per question):
    ## **CATEGORY NAME**                       (must be one of CATS below)
    ### **FAQ 12: The question?**
    **Answer:** Paragraph text...
    * bullet
Each category must contain exactly 30 questions (the script asserts this; change the
assert if the client's database grows). Hand-written FAQs and the SEO schema live in
src/data/faq.ts, so regenerating never overwrites them.
"""
import re, sys, json
src = sys.argv[1]
out = sys.argv[2] if len(sys.argv) > 2 else 'src/data/faq.generated.ts'
lines = open(src, encoding='utf8').read().split('\n')

CATS = {
  'COMPANY REGISTRATION': ('company-registration', 'Company Registration'),
  'GST & INCOME TAX':     ('gst-tax',              'GST & Income Tax'),
  'ROC COMPLIANCE':       ('roc-compliance',       'ROC Compliance'),
  'ACCOUNTING':           ('accounting',           'Accounting'),
  'TRADEMARK & IPR':      ('trademark-ipr',        'Trademark & IPR'),
}

def clean_inline(s):
    s = s.replace('\\.', '.').replace('\\-', '-')
    s = re.sub(r'\*\*(.+?)\*\*', r'\1', s)
    return s.strip()

def icon(q):
    ql = q.lower()
    rules = [
      ('clock',      r'how long|when |due date|deadline|timeline|within|how often|valid and|renew'),
      ('calculator', r'cost|fee|price|how much|capital|rate|refund|expense|cash flow|depreciation|tax audit|advance tax|valuation|shareholding|payroll'),
      ('globe',      r'foreign|nri|international|export|other countries|currency|domain|marketplace|social media|well-known'),
      ('shield',     r'penalt|notice|infring|protect|late|disqualif|mistake|objection|opposition|confidential|reject|closure|close |dormant|cancel|strike'),
      ('chart',      r'statement|report|mis |cfo|investor|reconcil|software|due diligence|accounting|bookkeeping|receivable|inventory'),
      ('document',   r'document|form |invoice|record|register|moa|aoa|dsc|din|bills|copyright|patent|design|spice|mgt|aoc|dir-3|adt|dpt|msme-1|name'),
    ]
    for name, pat in rules:
        if re.search(pat, ql): return name
    return 'building'

cats, cur, i = [], None, 0
while i < len(lines):
    l = lines[i]
    m = re.match(r'^## \*\*(.+?)\*\*\s*$', l)
    if m:
        key = m.group(1).strip()
        cid, label = CATS[key]
        cur = {'id': cid, 'label': label, 'items': []}; cats.append(cur); i += 1; continue
    m = re.match(r'^### \*\*FAQ \d+:\s*(.+?)\*\*\s*$', l)
    if m:
        q = clean_inline(m.group(1))
        j = i + 1; body = []
        while j < len(lines) and not lines[j].startswith('### ') and not lines[j].startswith('## ') and lines[j].strip() != '---':
            body.append(lines[j]); j += 1
        # first non-empty line holds "**Answer:** ..."
        k = next(n for n, b in enumerate(body) if b.strip())
        assert body[k].startswith('**Answer:**'), (q, body[k][:60])
        body[k] = body[k][len('**Answer:**'):].strip()
        blocks, para, bullets = [], [], []
        def flush():
            global para, bullets
            if para: blocks.append(' '.join(para)); para = []
            if bullets: blocks.append('\n'.join(bullets)); bullets = []
        for b in body[k:]:
            if not b.strip(): flush(); continue
            bm = re.match(r'^\s*[\*\-]\s+(.*)$', b)
            if bm:
                if para: flush()
                bullets.append('• ' + clean_inline(bm.group(1)))
            else:
                if bullets: flush()
                para.append(clean_inline(b))
        flush()
        cur['items'].append({'question': q, 'answer': '\n\n'.join(blocks), 'iconType': icon(q)})
        i = j; continue
    i += 1

assert len(cats) == 5 and all(len(c['items']) == 30 for c in cats), [(c['id'], len(c['items'])) for c in cats]

def ts_str(s): return json.dumps(s, ensure_ascii=False)

parts = ["""// AUTO-GENERATED by scripts/faq-from-markdown.py from the client's FAQ database.
// Do not edit by hand: change the markdown and re-run the script instead.
import type { FAQCategory } from './faq';

export const GENERATED_FAQ_CATEGORIES: FAQCategory[] = [
"""]
for c in cats:
    parts.append(f"    {{\n        id: {ts_str(c['id'])},\n        label: {ts_str(c['label'])},\n        items: [\n")
    for n, it in enumerate(c['items']):
        parts.append(f"            {{\n                question: {ts_str(it['question'])},\n                answer: {ts_str(it['answer'])},\n                iconType: '{it['iconType']}'\n            }}{',' if n < len(c['items'])-1 else ''}\n")
    parts.append("        ]\n    },\n")
parts.append("];\n")
open(out, 'w', encoding='utf8').write(''.join(parts))
print({c['id']: len(c['items']) for c in cats})
